ERROR_INPUT_DIALOG_UI = "ui/error_input.ui"
APPLY_SUCCESS_DIALOG_UI = "ui/apply_success_dialog.ui"
APPLY_REJECTED_DIALOG_UI = "ui/apply_rejected_dialog.ui"
EXCEED_MAX_AMOUNT_DIALOG_UI = "ui/exceed_max_amount_dialog.ui"
INTERFACE_FONT = "Helvetica"
BG_MAROON_0 = "rgb(91, 6, 22)"
BG_MAROON_1 = " rgb(136, 0, 0)"
